### ISSUE TITLE
How to dynamically construct data-bubb property and link callback

### ISSUE THREAD

**Issue by jithureddy** [frdnrdb/bubb#1]
Hi,

I have case where I repeat list using angular js ng-repeat and in html, I am generating data-bubb using repeated element id as below
`<div layout="column" data-bubb="{{::item._id}}-tooltip-data"></div>` 

Using directive I am constructing the bubb config for the above key as below:

` var tooltipDataId = element.parentElement.dataset.itemId + '-tooltip-data';
        var config = {
          
        }
        config[tooltipDataId] = {
          text: '',
          _: {
            callback: function (key, item) {
              item.innerHTML = 'Loading...';
              setTimeout(function(){
                item.innerHTML = 'I am done loading.'
              }, 750);
            },
            hoverCallback: true,
            interactive: false,
            transitionOff: true
          }
        }
        bubb(config);`

Tooltip is getting displayed for all the items but the content of the tooltip is not invoking from callback.
Please see this attachment
![image](https://user-images.githubusercontent.com/5911189/31001524-0daa0fbc-a502-11e7-9ebc-694e42682149.png)

Please help

**Comment by frdnrdb** [comment]
first - as i just pointed out [here](https://github.com/frdnrdb/bubb/issues?q=is%3Aopen+is%3Aissue): please excuse me for the long delay here; i published this project and then kind of forgot all about it :-)

next: yes - this was me thinking in the ways of "if someone doesn't specify a text/ content they're probably lazy and want the key/ reference itself to be the content". so: update bubb and this should be solved!
